### ISSUE TITLE
Feature Request LiveWire

### ISSUE THREAD

**Issue by ekandreas** [InteractionDesignFoundation/nova-html-card#10]
As for ->html and ->view it would be nice with a ->liveWire('my-livewire-component')
Sure, I can use views but...

**Comment by ekandreas** [comment]
Just reference the livewire blade directly works! Happy!

**Comment by lptn** [comment]
@ekandreas 
Could you please explain more so other users can use your info? Thanks!

**Comment by ekandreas** [comment]
Just call it! Eg,
```
return [
            (new HtmlCard())->width('1/3')->view('livewire.cards.my-awesome-livewire-component'),
];
```

**Comment by daggemarren** [comment]
How do you handle "wire:click" when loading your livewire components? all my functionallty is gone when loading livewire component with this example

**Comment by ekandreas** [comment]
I don't! Right now we can't get the Livewire to work in a html card as it is rendered as plain html-code and not as an interactive php component.

**Comment by lptn** [comment]
@daggemarren 
@ekandreas 
In our team we don't use livewire, so we don't have plans to support this. Feel free to create a PR for support it.

**Comment by ekandreas** [comment]
Sorry to hear that! The TALL stack is awesome!

**Comment by ekandreas** [comment]
Ok, then... Heard of Blade x-components in Laravel? Also a kind of dynamic rendering in blade...

**Comment by lptn** [comment]
@ekandreas 
that's a great idea! You re welcome to create a PR. We’ve added it to our backlog, but it as not a high priority, I assume we'll find a time for it in 1-2 months. So, you can help us to implement it faster ;)
