### ISSUE TITLE
forceFullWidth() like https://github.com/Krato/NovaTextCard

### ISSUE THREAD

**Issue by 4n70w4** [InteractionDesignFoundation/nova-html-card#11]
For fix https://github.com/InteractionDesignFoundation/nova-html-card/issues/5
https://github.com/Krato/NovaTextCard/blob/5f5ea5a1ea87881b623dd199c146aa6aaa66d516/resources/js/components/Card.vue#L54

**Comment by lptn** [comment]
@4n70w4 thanks for the idea! I just committed a fix, will release it soon
