### ISSUE TITLE
Feature request: auto refresh

### ISSUE THREAD

**Issue by internetbug256** [InteractionDesignFoundation/nova-html-card#12]
Hi. Thanks for your great contribution.
I wonder if there is a way to add the ability to define a refresh parameter.
I am using your card to show some status, and would like to auto-refresh every 10 secs or so.

**Comment by internetbug256** [comment]
Just for reference, this card implementation has exactly what I was suggesting:
https://github.com/devtropolis/nova-simple-status-card
'fetchInterval' => 5000

Thanks

**Comment by alies-dev** [comment]
Hey @internetbug256 

I like the idea, but I feel this is our of the responsibility of this package. But you can create a new package for this that will register a web-component with such control and you can use it together with this package. Unix way :)
