### ISSUE TITLE
Card does not expand to full height

### ISSUE THREAD

**Issue by bilogic** [InteractionDesignFoundation/nova-html-card#13]
![image](https://user-images.githubusercontent.com/946010/142608718-dfea74aa-01bc-48ef-ba5c-fd7ce2790506.png)

By default, the card does not expand to the same height as other cards due to the HTML class `htmlCard`, any reason for this?

**Comment by alies-dev** [comment]
I think it' fixed in our of our previous releases. Thanks for reporting, @bilogic !
