### ISSUE TITLE
[Question] How to pass data from the resource to the card

### ISSUE THREAD

**Issue by LorenzoSapora** [InteractionDesignFoundation/nova-html-card#14]
I am using these cards in `->onlyOnDetail()`, but cannot seem to get `$this->someColumn` in the html block. Is this even possible?

Example:

```php
public function cards(Request $request)
{
    return [
         (new HtmlCard)->onlyOnDetail()->html('<div>'.$this->id.'</div>')
    ];
}
```

`$this->id` displays nothing, but `$this->all()` displays the content 🤔 

I can pull the information manually, but I should have access to it already, but cannot work out _why not_

Thanks

**Comment by lptn** [comment]
hey @LorenzoSapora 

sorry, this question is not related to this package, it's about Nova itself. There are few related topic on laravel/nova-issues repo regarding this issue. You can try to use `$this->model()->id`. Alternatively you can explore  $request object or it's trait: `\Laravel\Nova\Http\Requests\InteractsWithResources`
