### ISSUE TITLE
Minor CSS issues when using withBasicStyles - hr, blockquote, and ol

### ISSUE THREAD

**Issue by bluec** [InteractionDesignFoundation/nova-html-card#30]
- Package Version: 3.2.0
- Nova Version: 4.3.15
- PHP Version: 8.3.x

### Description:

There's some minor CSS issues when rendering HTML/Markdown usng the `withBasicStyles` options: Horizontal rules have no margin so they stack on top of each other, Blockquotes don't indent, and ordered lists have no numbering.

<img width="1146" alt="Screenshot 2024-03-12 at 09 46 32" src="https://github.com/InteractionDesignFoundation/nova-html-card/assets/1577895/60c1f008-783d-48dd-ab26-d567fbff2e26">
<img width="1149" alt="Screenshot 2024-03-12 at 09 46 58" src="https://github.com/InteractionDesignFoundation/nova-html-card/assets/1577895/3d5b9544-3a71-4a66-9bd5-d13057007cb0">
<img width="1147" alt="Screenshot 2024-03-12 at 09 46 47" src="https://github.com/InteractionDesignFoundation/nova-html-card/assets/1577895/ef56529f-4b44-4a59-ac0e-6288f2a96f7b">

### Steps To Reproduce:

Here's some example markdown that will generate the screenshots above.

```

## Horizontal Rules

___

---

***

## Blockquotes


> Blockquotes can also be nested...
>> ...by using additional greater-than signs right next to each other...
> > > ...or with spaces between arrows.


Ordered

1. Lorem ipsum dolor sit amet
2. Consectetur adipiscing elit
3. Integer molestie lorem at massa

1. You can use sequential numbers...
1. ...or keep all the numbers as `1.`

Start numbering with offset:

57. foo
1. bar

```

Happy to raise a little PR to address these issues.

**Comment by bluec** [comment]
Here's some screenshots of the fixes as provided in #31 

<img width="1147" alt="Screenshot 2024-03-12 at 09 58 47" src="https://github.com/InteractionDesignFoundation/nova-html-card/assets/1577895/72283d3e-77ac-4f7a-ad0a-4a5c2563b7ff">
<img width="1148" alt="Screenshot 2024-03-12 at 09 58 56" src="https://github.com/InteractionDesignFoundation/nova-html-card/assets/1577895/c552a62f-387d-45ab-8b8b-e23a44762884">
<img width="1149" alt="Screenshot 2024-03-12 at 09 59 07" src="https://github.com/InteractionDesignFoundation/nova-html-card/assets/1577895/0fcf76ef-0753-4dc6-a5f1-ee75f580bedc">

**Comment by bluec** [comment]
> Hey @bluec
> 
> > Nova Version: 4.3.15
> 
> Just out of curiosity, why do you use such an old Nova version (and new PHP version at the same time)? Your answer may help me to understand the requirements for our Nova packages.
> 
> And thank you for your PR!

I think you have misread or misunderstood. That version of Nova was released less than 3 weeks ago: https://nova.laravel.com/releases

**Comment by alies-dev** [comment]
@bluec 
You probably mean v4.3**2**.15, right :)

**Comment by bluec** [comment]
> @bluec You probably mean v4.3**2**.15, right? :)

Ha yes well spotted
