### ISSUE TITLE
Ends up last if width('full')

### ISSUE THREAD

**Issue by fgilio** [InteractionDesignFoundation/nova-html-card#5]
Hi! I think this is a missing piece in Nova, so thanks a lot for building it.

I have one strange bug that may or may not be fixable by the package. If I use `width('full')` then the card ends up on the bottom of the page. It does not happen if I use `width('1/3')` or `width('1/2')`.

Here is my complete cards setup for that dashboard:
```php
public function cards()
{
    return [
        (new HtmlCard)->width('full')->html('Data might be up to 30 minutes old')->center(true),

        (new GlobalPets)->width('1/3'),
        (new GlobalOwners)->width('1/3'),
        (new GlobalVets)->width('1/3'),

        (new GlobalNewPets)->width('1/3'),
        (new GlobalPetsPerWeek)->width('2/3'),

        (new GlobalNewOwners)->width('1/3'),
        (new GlobalOwnersPerWeek)->width('2/3'),

        (new GlobalNewVets)->width('1/3'),
        (new GlobalVetsPerWeek)->width('2/3'),
    ];
}
```

**Comment by lptn** [comment]
Hey @fgilio 
Thanks for the report.

Actually this is a bug/feature in Nova. You can check `/nova-api/{resourceKey}/cards`  request and see that backend returns a valid order of cards. There is also nothing special on package's CSS to change the order. So, nothing to do in this package

**Comment by fgilio** [comment]
Ok! Thanks Alies! I'll open an issue in Nova's repo then.

**Comment by fgilio** [comment]
Already been reported here https://github.com/laravel/nova-issues/issues/1895

**Comment by lptn** [comment]
@fgilio

Latest 1.2.2 release has a new method to fix this issue. Please check https://github.com/InteractionDesignFoundation/nova-html-card/commit/0882447c573a242a893ae3038773633d6d0842ba

**Comment by fgilio** [comment]
Thanks @lptn !
