### ISSUE TITLE
Support for bare html cards

### ISSUE THREAD

**Issue by tpetry** [InteractionDesignFoundation/nova-html-card#6]
At the moment your fantastic package is trying to mimic novas card layout with it‘s border, rounded edges and padding. This is very useful and we have been able to build some cards which look nova-like.

I wish for an option to remove this styling completely. Say you want to render e.g. an alert on top of a resources record. Nova does not have this and there are no packages for it. And displaying it within a card looks strange. So in some cases it would be nice to be able to render a „card“ without any predefined styling and defaults so you can completely design it to your custom needs.

There are many different cases where someone would like to tune the styling a little bit. And this is the most easy if you can start from a blank space without any defaults being set.

**Comment by lptn** [comment]
Hey @tpetry 
Thanks for your feedback and the question.  That's a really cool feature-request! I think we'll implement it soon!

**Comment by lptn** [comment]
Hey @tpetry 
I've created a new branch with `withoutCardStyles()` option: `withoutCardStyles-option`. Could you please try it and leave feedback how it covers your needs.  Thanks!

**Comment by tpetry** [comment]
Works perfectly 👍
